/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ApiPublicIngestJobsRouteImport } from './routes/api/public/ingest-jobs'
import { Route as ApiPublicMatchCitiesRouteImport } from './routes/api/public/match-cities'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestJobsRoute = ApiPublicIngestJobsRouteImport.update({
  id: '/api/public/ingest-jobs',
  path: '/api/public/ingest-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMatchCitiesRoute = ApiPublicMatchCitiesRouteImport.update({
  id: '/api/public/match-cities',
  path: '/api/public/match-cities',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/api/public/ingest-jobs': typeof ApiPublicIngestJobsRoute
  '/api/public/match-cities': typeof ApiPublicMatchCitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/api/public/ingest-jobs': typeof ApiPublicIngestJobsRoute
  '/api/public/match-cities': typeof ApiPublicMatchCitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/api/public/ingest-jobs': typeof ApiPublicIngestJobsRoute
  '/api/public/match-cities': typeof ApiPublicMatchCitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/insights' | '/api/public/ingest-jobs' | '/api/public/match-cities'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/insights' | '/api/public/ingest-jobs' | '/api/public/match-cities'
  id:
    | '__root__'
    | '/'
    | '/insights'
    | '/api/public/ingest-jobs'
    | '/api/public/match-cities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsightsRoute: typeof InsightsRoute
  ApiPublicIngestJobsRoute: typeof ApiPublicIngestJobsRoute
  ApiPublicMatchCitiesRoute: typeof ApiPublicMatchCitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-jobs': {
      id: '/api/public/ingest-jobs'
      path: '/api/public/ingest-jobs'
      fullPath: '/api/public/ingest-jobs'
      preLoaderRoute: typeof ApiPublicIngestJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/match-cities': {
      id: '/api/public/match-cities'
      path: '/api/public/match-cities'
      fullPath: '/api/public/match-cities'
      preLoaderRoute: typeof ApiPublicMatchCitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsightsRoute: InsightsRoute,
  ApiPublicIngestJobsRoute: ApiPublicIngestJobsRoute,
  ApiPublicMatchCitiesRoute: ApiPublicMatchCitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
